In [1]:
from sklearn import preprocessing
from sklearn.svm import SVC
import pandas as pd
from sklearn.metrics import accuracy_score
import numpy as np

In [2]:
X_train_30sec_F = pd.read_csv('/home/satishk/GAN_lre/gan_csv/10sec_to_30sec_data/X_train_30sec_F.csv')

y_30sec_labels_train = pd.read_csv('/home/satishk/GAN_lre/gan_csv/10sec_to_30sec_data/y_30sec_labels_train.csv')

train_X_gen_30 = pd.read_csv('/home/satishk/GAN_lre/gan_csv/10sec_to_30sec_data/train_X_gen.csv')

X_val_gen_30 = pd.read_csv('/home/satishk/GAN_lre/gan_csv/10sec_to_30sec_data/X_val_gen.csv')

#X_val = pd.read_csv('/home/satishk/GAN_lre/gan_csv/10sec_to_30sec_data/X_val.csv')

y_val_labels_30 = pd.read_csv('/home/satishk/GAN_lre/gan_csv/10sec_to_30sec_data/y_val_labels.csv')

In [3]:
X_train_30sec_F.head()

0         1         2         3         4         5         6  \
0  0.543980  1.907223  0.845941 -1.264026  1.519903  1.206621 -1.145104   
1  0.676368 -1.635733  0.301036  0.023667 -1.218303  0.685264 -3.631188   
2  0.895602 -1.382061  0.298067  0.323601 -1.088163  0.901107 -3.269509   
3 -0.914272  0.916085  1.381481 -0.894685 -1.687538  1.383119 -0.103527   
4 -0.562137 -0.693981  1.948308  1.763946  0.795333  0.965096 -0.545974   

          7         8         9    ...          490       491       492  \
0 -1.304972  1.327695 -0.083653    ...     1.717214 -0.572291  1.138699   
1 -0.604528 -0.343538  0.031158    ...    -0.840792 -1.437651  1.402903   
2 -1.103945 -0.445049 -1.021641    ...    -1.041714 -1.867680  0.151127   
3 -0.928042  0.115846  0.135984    ...     0.874826  0.293716 -0.725702   
4  0.670981 -1.034974  0.299159    ...    -1.388793 -1.073850  2.046929   

        493       494       495       496       497       498       499  
0 -1.651893 -1.165604 -1.629220  1.401991  1.114939 -0.438683 -1.245293  
1 -1.971690 -0.189517 -0.574338  1.672668 -0.650887  0.467424  0.751408  
2  0.910858 -0.867748 -1.316548  0.728499  0.216339  0.794277  1.842972  
3 -1.213329 -0.747443  1.082053  0.367150  0.749275 -1.136481 -0.244752  
4  1.532768  0.773104  0.029967 -0.499692  0.067440 -1.272006  0.166963  

[5 rows x 500 columns]

In [4]:
X_train_30sec_F.values.shape

(91420, 500)

In [5]:
y_30sec_labels_train.values.shape

(91420, 1)

In [6]:
train_X_gen_30.values.shape

(91420, 500)

In [7]:
X_val_gen_30.values.shape

(928, 500)

In [8]:
y_val_labels_30.values.shape

(928, 1)

In [9]:
train_X_gen_10 = pd.read_csv('/home/satishk/GAN_lre/gan_csv/3sec_to_10sec_data/train_X_gen.csv')

y_10sec_labels_train = pd.read_csv('/home/satishk/GAN_lre/gan_csv/3sec_to_10sec_data/y_10sec_labels_train.csv')

X_val_gen_10 = pd.read_csv('/home/satishk/GAN_lre/gan_csv/3sec_to_10sec_data/X_val_gen.csv')

y_val_labels_10 = pd.read_csv('/home/satishk/GAN_lre/gan_csv/3sec_to_10sec_data/y_val_labels.csv')

In [10]:
train_X_gen_F = pd.concat([train_X_gen_30, train_X_gen_10, X_train_30sec_F], axis=0)

In [11]:
#train_X_gen_F.isnull().values.any()


In [12]:
train_X_gen_F.shape

(470946, 500)

In [13]:
y_labels_train_F = pd.concat([y_30sec_labels_train, y_10sec_labels_train, y_30sec_labels_train], axis=0)

In [14]:
#y_labels_train_F.isnull().values.any()


In [15]:
y_labels_train_F.shape

(470946, 1)

In [16]:
y_10sec_labels_train.values.shape

(288106, 1)

In [17]:
train_X_gen_10.values.shape

(288106, 500)

In [18]:
X_val_gen_10.values.shape

(926, 500)

In [19]:
#X_val.values.shape

In [20]:
y_val_labels_10.values.shape

(926, 1)

In [21]:
val_lre = pd.read_csv('/home/satishk/GAN_lre/gan_csv/dev_feat_BNF_h5_07Feb_30sec.csv')


In [22]:
val_lre.head()

0         1         2         3         4         5         6  \
0 -0.888892 -0.725549  1.228262  2.474089 -0.136339  1.062172 -0.099022   
1  1.942636 -0.608172  0.063426  0.523868 -1.865434  1.296230 -0.838107   
2  0.301494  0.195578  0.098511  0.674540 -0.690160  1.490930  2.754279   
3  1.462617  1.071120  0.594702 -0.443542 -0.582299  1.577922 -0.555321   
4  1.361938 -0.535247 -0.407092  0.194813 -0.274774  1.175021  1.504898   

          7         8         9       ...             495       496       497  \
0 -0.470705  1.654063 -1.702971       ...        0.208072  0.467385 -0.336328   
1  1.209962  1.195006  0.243069       ...       -1.585508  1.065699 -0.015363   
2 -0.065669 -0.866126 -0.027248       ...        1.051669  1.594601 -1.789852   
3 -0.233825  2.594382  0.310931       ...       -1.196281  0.461040  0.002523   
4  0.557574  0.672867  1.440742       ...        1.558112  0.266925  0.114382   

        498       499           uttid  language_code  data_source  \
0  1.096394 -1.589369  lre17_jxjmxcks        spa-lac        mls14   
1 -2.215722  1.996507  lre17_wuiwqisj        ara-acm        mls14   
2  0.820086 -0.911528  lre17_ssnynfsd        qsl-pol        mls14   
3  1.228467  0.395093  lre17_mfwrkmia        eng-usg        mls14   
4 -0.898504  0.915694  lre17_ycoxrura        ara-apc        mls14   

   speech_duration      segmentid1  
0               30  lre17_jxjmxcks  
1               30  lre17_wuiwqisj  
2               30  lre17_ssnynfsd  
3               30  lre17_mfwrkmia  
4               30  lre17_ycoxrura  

[5 rows x 505 columns]

In [23]:
X_val_30_orig = val_lre.drop(["language_code","uttid","segmentid1","data_source","speech_duration"],axis=1)
y_val_30_orig = val_lre["language_code"]

In [24]:
y_val_30_orig.head()

0    spa-lac
1    ara-acm
2    qsl-pol
3    eng-usg
4    ara-apc
Name: language_code, dtype: object

In [25]:
le = preprocessing.LabelEncoder()
le.fit(y_val_30_orig)

LabelEncoder()

In [26]:
le.classes_

array(['ara-acm', 'ara-apc', 'ara-ary', 'ara-arz', 'eng-gbr', 'eng-usg',
       'por-brz', 'qsl-pol', 'qsl-rus', 'spa-car', 'spa-eur', 'spa-lac',
       'zho-cmn', 'zho-nan'], dtype=object)

In [27]:
y_val_labels_30_orig = le.transform(y_val_30_orig)

In [28]:
type(y_val_labels_30_orig)

numpy.ndarray

In [29]:
y_val_labels_30_orig

array([11,  0,  7,  5,  1,  5,  8,  1,  0, 13, 10,  3, 13, 12, 12,  6,  5,
        2,  5, 11,  6, 12,  5, 12,  1,  0, 10,  5,  4,  4,  2,  1,  4, 10,
       11,  0,  0,  1, 13,  0,  5, 13,  7,  2,  5,  5, 12,  2,  5, 10, 12,
       13,  6,  0,  3, 12,  3,  4,  2,  7, 11,  9,  2,  9,  0,  5,  1,  4,
        5, 10,  1,  3, 13,  3,  4,  3,  3,  2, 10,  2, 11,  7,  2, 10,  0,
        3,  4, 13, 10,  0, 11,  5, 13,  8,  6, 10,  8,  2,  1,  7,  4,  0,
        2,  3,  2,  3,  3,  1, 11,  0,  0, 12,  1,  3, 10, 13,  3, 10,  0,
        6, 13,  3,  2,  3, 11,  1,  2,  1, 13,  1,  5,  5,  8,  5,  0,  3,
        2, 13, 11,  2, 13, 13,  0,  6,  5, 13,  6,  7, 10,  4,  8, 12,  6,
       13,  6,  2, 13,  7, 10,  9,  7, 12,  1, 11, 11, 12,  1, 12, 11,  7,
        3,  8,  2,  4,  1,  3, 11,  3, 11,  3,  2,  6, 10,  4,  0,  3, 12,
        8, 13, 12,  9,  2, 11,  3,  1,  4, 10,  5, 11,  8,  6,  2,  1,  3,
       13, 12,  7,  5,  0,  2,  5,  2,  5, 13,  4, 12, 11, 10,  3,  3,  7,
        2, 13,  1,  2,  5

In [30]:
type(y_val_labels_30_orig)

numpy.ndarray

In [31]:
y_val_labels_30_orig.shape

(933,)

In [32]:
y_val_labels_30_orig2 =y_val_labels_30_orig.reshape(933,1)

In [33]:
y_val_labels_30_orig2

array([[11],
       [ 0],
       [ 7],
       [ 5],
       [ 1],
       [ 5],
       [ 8],
       [ 1],
       [ 0],
       [13],
       [10],
       [ 3],
       [13],
       [12],
       [12],
       [ 6],
       [ 5],
       [ 2],
       [ 5],
       [11],
       [ 6],
       [12],
       [ 5],
       [12],
       [ 1],
       [ 0],
       [10],
       [ 5],
       [ 4],
       [ 4],
       [ 2],
       [ 1],
       [ 4],
       [10],
       [11],
       [ 0],
       [ 0],
       [ 1],
       [13],
       [ 0],
       [ 5],
       [13],
       [ 7],
       [ 2],
       [ 5],
       [ 5],
       [12],
       [ 2],
       [ 5],
       [10],
       [12],
       [13],
       [ 6],
       [ 0],
       [ 3],
       [12],
       [ 3],
       [ 4],
       [ 2],
       [ 7],
       [11],
       [ 9],
       [ 2],
       [ 9],
       [ 0],
       [ 5],
       [ 1],
       [ 4],
       [ 5],
       [10],
       [ 1],
       [ 3],
       [13],
       [ 3],
       [ 4],
       [ 3],
       [ 3],

In [34]:
type(y_val_labels_30.values)

numpy.ndarray

In [35]:
y_val_labels_30.values

array([[13],
       [ 5],
       [12],
       [ 5],
       [11],
       [11],
       [11],
       [12],
       [10],
       [ 0],
       [11],
       [ 0],
       [ 2],
       [13],
       [12],
       [ 6],
       [13],
       [ 4],
       [ 6],
       [ 0],
       [11],
       [ 2],
       [ 4],
       [ 3],
       [10],
       [ 4],
       [ 3],
       [ 4],
       [10],
       [ 1],
       [10],
       [13],
       [11],
       [ 1],
       [ 3],
       [12],
       [12],
       [ 4],
       [ 4],
       [ 0],
       [ 9],
       [ 0],
       [ 2],
       [ 3],
       [13],
       [12],
       [ 2],
       [ 6],
       [ 5],
       [ 4],
       [ 9],
       [ 2],
       [ 1],
       [13],
       [ 9],
       [ 2],
       [13],
       [12],
       [13],
       [ 3],
       [ 0],
       [ 5],
       [ 4],
       [ 0],
       [ 1],
       [ 3],
       [ 2],
       [10],
       [12],
       [10],
       [ 0],
       [ 0],
       [ 2],
       [ 5],
       [ 6],
       [13],
       [ 0],

In [36]:
type(y_val_labels_30.values)

numpy.ndarray

In [37]:
y_val_labels_30.values

array([[13],
       [ 5],
       [12],
       [ 5],
       [11],
       [11],
       [11],
       [12],
       [10],
       [ 0],
       [11],
       [ 0],
       [ 2],
       [13],
       [12],
       [ 6],
       [13],
       [ 4],
       [ 6],
       [ 0],
       [11],
       [ 2],
       [ 4],
       [ 3],
       [10],
       [ 4],
       [ 3],
       [ 4],
       [10],
       [ 1],
       [10],
       [13],
       [11],
       [ 1],
       [ 3],
       [12],
       [12],
       [ 4],
       [ 4],
       [ 0],
       [ 9],
       [ 0],
       [ 2],
       [ 3],
       [13],
       [12],
       [ 2],
       [ 6],
       [ 5],
       [ 4],
       [ 9],
       [ 2],
       [ 1],
       [13],
       [ 9],
       [ 2],
       [13],
       [12],
       [13],
       [ 3],
       [ 0],
       [ 5],
       [ 4],
       [ 0],
       [ 1],
       [ 3],
       [ 2],
       [10],
       [12],
       [10],
       [ 0],
       [ 0],
       [ 2],
       [ 5],
       [ 6],
       [13],
       [ 0],

In [38]:
y_val_labels_30 = pd.DataFrame(y_val_labels_30.values)
y_val_labels_10 = pd.DataFrame(y_val_labels_10.values)
y_val_labels_30_orig2 = pd.DataFrame(y_val_labels_30_orig2)

In [39]:
y_labels_val_F = pd.concat([y_val_labels_30, y_val_labels_10, y_val_labels_30_orig2], axis=0)

In [40]:
y_labels_val_F.shape

(2787, 1)

In [41]:
X_val_F = pd.concat([X_val_gen_30, X_val_gen_10, X_val_30_orig], axis=0)

In [42]:
X_val_F.shape

(2787, 500)

In [43]:
train_X_gen_F = train_X_gen_F.values
y_labels_train_F = y_labels_train_F.values
X_val_F = X_val_F.values
y_labels_val_F = y_labels_val_F.values

In [44]:
train_X_gen_F.shape

(470946, 500)

In [45]:
y_labels_train_F.shape

(470946, 1)

In [46]:
y_labels_val_F.shape

(2787, 1)

In [47]:
#y_labels_train_F = y_labels_train_F.T

In [48]:
#y_labels_val_F = y_labels_val_F.T

In [ ]:
y_labels_train_F = y_labels_train_F.reshape(470946,)
y_labels_val_F = y_labels_val_F.reshape(2787,)

In [ ]:
classif = SVC(C=1, kernel='poly', degree=2, gamma='auto', coef0=1, shrinking=True, random_state=0,
              probability=False, tol=1e-3, cache_size=1e4, class_weight='balanced')
classif.fit(train_X_gen_F, y_labels_train_F)

In [ ]:
classif.classes_

In [ ]:
acc = accuracy_score(y_labels_val_F, classif.predict(X_val_F))

In [ ]:
acc

In [ ]:
from sklearn.externals import joblib

In [ ]:
filename = '/home/satishk/GAN_lre/gan_csv/digits_classifier.joblib.pkl'

In [ ]:
_ = joblib.dump(classif, filename, compress=9)